---

- block:

  - name: Uninstall unused packages
    pacman:
      name:
        - bandwidth
        - jdk8-openjdk
        - jq
        - maven
        - python-rst2pdf
        - python36
        - sbt
        - scala
        - spin
      state: absent

  - name: Install development tools
    pacman:
      name:
        - ansible
        - ansible-lint
        - cmark
        - ctags
        - desktop-file-utils
        - devtools
        - entr
        - git
        - gobject-introspection
        - graphviz
        - heaptrack
        - ipv6calc
        - mypy
        - namcap
        - pacman-contrib
        - postgresql-libs  # for iqe-tests
        - python-dnspython  # for ansible's dig lookup plugin
        - python-docutils  # for rst2html
        - python-passlib  # for ansible's htpasswd module
        - python-poetry
        - python-pylint
        - python-sphinx
        - python-wheel
        - rust
        - rust-docs
        - shellcheck
        - sshpass  # optional for ansible
        - tmate
        - tmux
        - twine
        - vim
        - vim-nerdtree
        - vim-tagbar
        - wget
        - yamllint
    notify: Set install reason for optional dependencies

  become: true
