session_name: redhat
windows:
  - window_name: vim
    start_directory: ~/code/redhat
    panes:
      - vim ~/Documents/source/redhat/scratchpad.rst

  - window_name: remediations
    layout: even-vertical
    start_directory: ~/code/redhat/iqe-remediations-plugin
    panes:
      - focus: true
        shell_command:
          - . ~/.venvs/iqe-remediations-plugin/bin/activate
          - git status
      - watch --color git hist --color

  - window_name: rhc
    layout: even-vertical
    start_directory: ~/code/redhat/iqe-rhc-plugin
    panes:
      - focus: true
        shell_command:
          - . ~/.venvs/iqe-rhc-plugin/bin/activate
          - git status
      - watch --color git hist --color

  - window_name: e2e
    layout: even-vertical
    start_directory: ~/code/redhat/iqe-e2e-plugin
    panes:
      - focus: true
        shell_command:
          - . ~/.venvs/iqe-e2e-plugin/bin/activate
          - git status
      - watch --color git hist --color

  - window_name: config manager
    layout: even-vertical
    start_directory: ~/code/redhat/config-manager
    panes:
      - focus: true
        shell_command:
          - git status
          - docker-compose ps
      - watch --color git hist --color
