---
- name: Assert required variables have been set
  assert:
    that:
      - nftables_branch_downstream_if is defined
      - nftables_branch_upstream_if is defined

- block:

  - name: Install nftables
    pacman:
      name: nftables

  - name: Install nftables configuration file
    template:
      src: nftables.conf
      dest: /etc/nftables.conf
    notify: Reload nftables

  - name: Start and enable nftables
    systemd:
      name: nftables.service
      state: started
      enabled: true
      daemon_reload: true

  become: true
